services:
  app:
    image: ghcr.io/alexpresso/zunivers-ninja:latest
    container_name: zunivers-ninja
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_PASSWORD=PASSWORD # change PASSWORD
      - DISCORD_TAGS=alexpresso # discord usernames (coma separated)
      # - WEBHOOK_URL=https://discord.com/api/webhooks/123456789/token-abcd # (Optional) Set your channel Discord webhook URL
    depends_on:
      neo4j:
        condition: service_healthy
  neo4j:
    image: neo4j:latest
    container_name: zunivers-ninja-neo4j
    environment:
      - NEO4J_AUTH=neo4j/PASSWORD # change PASSWORD
    # ports:
    #   - 7474:7474 # Optional Db UI
    #   - 7687:7687 # Optional Db Listen address
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 30s
      timeout: 20s
      retries: 3
