apiVersion: apps/v1
kind: Deployment
metadata:
  name: zunivers-ninja
spec:
  selector:
    matchLabels:
      name: zunivers-ninja
  template:
    metadata:
      labels:
        name: zunivers-ninja
    spec:
      containers:
        - name: application
          image: openjdk
          imagePullPolicy: Always
          command:
            - sh
            - -exc
            - |
              curl 'https://maven.pkg.github.com/alexpresso/zunivers-ninja/me/alexpresso/zunivers-ninja/{{ .Values.version }}/zunivers-ninja-{{ .Values.version }}.jar' \
              -H "Authorization: Bearer {{ .Values.githubToken }}" \
              -L \
              -o zunivers-ninja.jar && \
              java -jar zunivers-ninja.jar
          resources:
            requests:
              cpu: 100m
              memory: 1000m
          volumeMounts:
            - name: zu-ninja-config-vol
              mountPath: /config
              subPath: config.json
            - name: timezone
              mountPath: /etc/localtime
              subPath: Europe/Paris
              readOnly: true
      volumes:
        - name: zu-ninja-config-vol
          configMap:
            name: zu-ninja-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo