spring.neo4j:
  uri: bolt://127.0.0.1:7687
  authentication:
    username: neo4j
    password: changeme

toolkit:
  discordTags: alexpresso
  runAutomatedTasks: false

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com

webhookUrl: #Use your own

logging:
  level:
    me.alexpresso.zuninja: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
