spring.neo4j:
  uri: bolt://localhost:7687
  authentication:
    username: neo4j
    password: password

toolkit:
  discordTag: Alex'Presso#5480

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com