spring.neo4j:
  uri: bolt://localhost:7687
  authentication:
    username: neo4j
    password: password

toolkit:
  discordTag: Alex'Presso#5480
  runAutomatedTasks: true
  refreshToken:

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com
  keycloakBaseUrl: keycloak-zunivers-prod.prod.poneyy.fr
  keycloakClientId: zunivers

webhookUrl: #insert your own (facultative)

#Could be: score or collection
goal: collection

logging:
  level:
    me.alexpresso.zuninja: INFO
