spring.neo4j:
  uri: ${NEO4J_URI:bolt://127.0.0.1:7687}
  authentication:
    username: ${NEO4J_USERNAME:neo4j}
    password: ${NEO4J_PASSWORD:changeme}

toolkit:
  discordTags: ${DISCORD_TAGS:alexpresso}
  runAutomatedTasks: ${RUN_AUTOMATED_TASKS:false}

zunivers:
  apiBaseUrl: ${API_BASE_URL:zunivers-api.zerator.com}
  frontBaseUrl: ${FRONT_BASE_URL:zunivers.zerator.com}

webhookUrl: ${WEBHOOK_URL} #Use your own

logging:
  level:
    me.alexpresso.zuninja: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
