spring.neo4j:
  uri: bolt://localhost:7687
  authentication:
    username: neo4j
    password: password

toolkit:
  discordTags:
    - Alex'Presso#5480
  runAutomatedTasks: true

zunivers:
  apiBaseUrl: zunivers-api.zerator.com
  frontBaseUrl: zunivers.zerator.com

webhookUrl: #insert your own (facultative)

logging:
  level:
    me.alexpresso.zuninja: INFO
